import 'package:dhikr/Controller/NameClass.dart';

final List<AllahName> allahNamesBangla = [
  AllahName(name: 'ٱلْرَّحْمَـانُ', meaning: 'পরম দয়ালু'),
  AllahName(name: 'ٱلْرَّحِيْمُ', meaning: 'করুণাময়'),
  AllahName(name: 'ٱلْمَلِكُ', meaning: 'মহাসত্তা ও শাসক'),
  AllahName(name: 'ٱلْقُدُّوسُ', meaning: 'সম্পূর্ণ পবিত্র'),
  AllahName(name: 'ٱلْسَّلَامُ', meaning: 'শান্তি দানকারী'),
  AllahName(name: 'ٱلْمُؤْمِنُ', meaning: 'বিশ্বাস দানকারী'),
  AllahName(name: 'ٱلْمُهَيْمِنُ', meaning: 'নিরাপত্তা প্রদানকারী'),
  AllahName(name: 'ٱلْعَزِيزُ', meaning: 'পরাক্রমশালী'),
  AllahName(name: 'ٱلْجَبَّارُ', meaning: 'পরাক্রমশালী ও পুনরুদ্ধারকারী'),
  AllahName(name: 'ٱلْمُتَكَبِّرُ', meaning: 'মহান'),
  AllahName(name: 'ٱلْخَالِقُ', meaning: 'সৃষ্টিকর্তা'),
  AllahName(name: 'ٱلْبَارِئُ', meaning: 'সৃজনকারী'),
  AllahName(name: 'ٱلْمُصَوِّرُ', meaning: 'আকৃতি দানকারী'),
  AllahName(name: 'ٱلْغَفَّارُ', meaning: 'অত্যন্ত ক্ষমাশীল'),
  AllahName(name: 'ٱلْقَهَّارُ', meaning: 'জয়ী ও অধিকারকারী'),
  AllahName(name: 'ٱلْوَهَّابُ', meaning: 'উপহার দানকারী'),
  AllahName(name: 'ٱلْرَّزَّاقُ', meaning: 'রিজিক দানকারী'),
  AllahName(name: 'ٱلْفَتَّاحُ', meaning: 'সিদ্ধান্তদাতা'),
  AllahName(name: 'ٱلْعَلِيمُ', meaning: 'পরিপূর্ণ জ্ঞানী'),
  AllahName(name: 'ٱلْقَابِضُ', meaning: 'সংকোচনকারী'),
  AllahName(name: 'ٱلْبَاسِطُ', meaning: 'প্রসারণকারী'),
  AllahName(name: 'ٱلْخَافِضُ', meaning: 'অবনতকারী'),
  AllahName(name: 'ٱلْرَّافِعُ', meaning: 'উন্নতকারী'),
  AllahName(name: 'ٱلْمُعِزُّ', meaning: 'সম্মান দানকারী'),
  AllahName(name: 'ٱلْمُذِلُّ', meaning: 'অপমানকারী'),
  AllahName(name: 'ٱلْسَّمِيعُ', meaning: 'শ্রবণকারী'),
  AllahName(name: 'ٱلْبَصِيرُ', meaning: 'দ্রষ্টা'),
  AllahName(name: 'ٱلْحَكَمُ', meaning: 'বিচারক'),
  AllahName(name: 'ٱلْعَدْلُ', meaning: 'ন্যায়বিচারক'),
  AllahName(name: 'ٱلْلَّطِيفُ', meaning: 'সুকোমল'),
  AllahName(name: 'ٱلْخَبِيرُ', meaning: 'সম্যক জ্ঞানী'),
  AllahName(name: 'ٱلْحَلِيمُ', meaning: 'অধৈর্য'),
  AllahName(name: 'ٱلْعَظِيمُ', meaning: 'মহান'),
  AllahName(name: 'ٱلْغَفُورُ', meaning: 'ক্ষমাশীল'),
  AllahName(name: 'ٱلْشَّكُورُ', meaning: 'কৃতজ্ঞ'),
  AllahName(name: 'ٱلْعَلِيُّ', meaning: 'উচ্চতম'),
  AllahName(name: 'ٱلْكَبِيرُ', meaning: 'মহান'),
  AllahName(name: 'ٱلْحَفِيظُ', meaning: 'রক্ষক'),
  AllahName(name: 'ٱلْمُقِيتُ', meaning: 'পুষ্টি দানকারী'),
  AllahName(name: 'ٱلْحَسِيبُ', meaning: 'পর্যাপ্ত'),
  AllahName(name: 'ٱلْجَلِيلُ', meaning: 'মহানুভব'),
  AllahName(name: 'ٱلْكَرِيمُ', meaning: 'উদার'),
  AllahName(name: 'ٱلْرَّقِيبُ', meaning: 'পর্যবেক্ষণকারী'),
  AllahName(name: 'ٱلْمُجِيبُ', meaning: 'প্রতিক্রিয়াশীল'),
  AllahName(name: 'ٱلْوَاسِعُ', meaning: 'সর্বব্যাপী'),
  AllahName(name: 'ٱلْحَكِيمُ', meaning: 'জ্ঞাণী'),
  AllahName(name: 'ٱلْوَدُودُ', meaning: 'প্রেমময়'),
  AllahName(name: 'ٱلْمَجِيدُ', meaning: 'মহান'),
  AllahName(name: 'ٱلْبَاعِثُ', meaning: 'পুনরুত্থানকারী'),
  AllahName(name: 'ٱلْشَّهِيدُ', meaning: 'সাক্ষী'),
  AllahName(name: 'ٱلْحَقُّ', meaning: 'সত্য'),
  AllahName(name: 'ٱلْوَكِيلُ', meaning: 'অভিভাবক'),
  AllahName(name: 'ٱلْقَوِيُّ', meaning: 'শক্তিমান'),
  AllahName(name: 'ٱلْمَتِينُ', meaning: 'দৃঢ়'),
  AllahName(name: 'ٱلْوَلِيُّ', meaning: 'সুরক্ষক'),
  AllahName(name: 'ٱلْحَمِيدُ', meaning: 'প্রশংসিত'),
  AllahName(name: 'ٱلْمُحْصِيُ', meaning: 'গণনাকারী'),
  AllahName(name: 'ٱلْمُبْدِئُ', meaning: 'আদি স্রষ্টা'),
  AllahName(name: 'ٱلْمُعِيدُ', meaning: 'পুনরায় ফিরিয়ে আনার ক্ষমতাবান'),
  AllahName(name: 'ٱلْمُحْيِى', meaning: 'জীবন দানকারী'),
  AllahName(name: 'ٱلْمُمِيتُ', meaning: 'মৃত্যু দানকারী'),
  AllahName(name: 'ٱلْحَىُّ', meaning: 'চিরঞ্জীব'),
  AllahName(name: 'ٱلْقَيُّومُ', meaning: 'চিরস্থায়ী'),
  AllahName(name: 'ٱلْوَاجِدُ', meaning: 'অবিস্মরণীয়'),
  AllahName(name: 'ٱلْمَاجِدُ', meaning: 'গৌরবান্বিত'),
  AllahName(name: 'ٱلْوَاحِدُ', meaning: 'অদ্বিতীয়'),
  AllahName(name: 'ٱلْأَحَد', meaning: 'একক'),
  AllahName(name: 'ٱلْصَّمَدُ', meaning: 'চিরস্থায়ী'),
  AllahName(name: 'ٱلْقَادِرُ', meaning: 'সর্বশক্তিমান'),
  AllahName(name: 'ٱلْمُقْتَدِرُ', meaning: 'সর্বশক্তিমান'),
  AllahName(name: 'ٱلْمُقَدِّمُ', meaning: 'অগ্রবর্তী'),
  AllahName(name: 'ٱلْمُؤَخِّرُ', meaning: 'পিছন সরানোকারী'),
  AllahName(name: 'ٱلأَوَّلُ', meaning: 'প্রথম'),
  AllahName(name: 'ٱلْآخِرُ', meaning: 'শেষ'),
  AllahName(name: 'ٱلْظَّاهِرُ', meaning: 'প্রকাশিত'),
  AllahName(name: 'ٱلْبَاطِنُ', meaning: 'গোপনীয়'),
  AllahName(name: 'ٱلْوَالِي', meaning: 'প্রশাসক'),
  AllahName(name: 'ٱلْمُتَعَالِي', meaning: 'উচ্চতর'),
  AllahName(name: 'ٱلْبَرُّ', meaning: 'সকল কল্যাণের উৎস'),
  AllahName(name: 'ٱلْتَّوَّابُ', meaning: 'অনুতাপগ্রহণকারী'),
  AllahName(name: 'ٱلْمُنْتَقِمُ', meaning: 'প্রতিশোধগ্রহণকারী'),
  AllahName(name: 'ٱلْعَفُوُّ', meaning: 'ক্ষমাকারী'),
  AllahName(name: 'ٱلْرَّؤُفُ', meaning: 'পরম দয়ালু'),
  AllahName(name: 'مَالِكُ ٱلْمُلْكُ', meaning: 'রাজত্বের অধিকারী'),
  AllahName(
      name: 'ذُو ٱلْجَلَالِ وَٱلْإِكْرَامُ',
      meaning: 'মহিমা ও সম্মানের অধিকারী'),
  AllahName(name: 'ٱلْمُقْسِطُ', meaning: 'ন্যায়পরায়ণ'),
  AllahName(name: 'ٱلْجَامِعُ', meaning: 'সংগ্রহকারী'),
  AllahName(name: 'ٱلْغَنيُّ', meaning: 'স্বয়ংসম্পূর্ণ'),
  AllahName(name: 'ٱلْمُغْنِيُّ', meaning: 'অর্থ প্রদানকারী'),
  AllahName(name: 'ٱلْمَانِعُ', meaning: 'অবরোধকারী'),
  AllahName(name: 'ٱلْضَّارُ', meaning: 'ক্ষতিকর'),
  AllahName(name: 'ٱلْنَّافِعُ', meaning: 'উপকারী'),
  AllahName(name: 'ٱلْنُّورُ', meaning: 'আলোকদাতা'),
  AllahName(name: 'ٱلْهَادِي', meaning: 'পথপ্রদর্শক'),
  AllahName(name: 'ٱلْبَدِيعُ', meaning: 'অনন্য স্রষ্টা'),
  AllahName(name: 'ٱلْبَاقِي', meaning: 'অবিনশ্বর'),
  AllahName(name: 'ٱلْوَارِثُ', meaning: 'উত্তরাধিকারী'),
  AllahName(name: 'ٱلْرَّشِيدُ', meaning: 'সঠিক পথ প্রদর্শক'),
  AllahName(name: 'ٱلْصَّبُورُ', meaning: 'ধৈর্যশীল')
];
