import 'package:dhikr/Controller/NameClass.dart';

final List<AllahName> allahNames = [
  AllahName(name: 'ٱلْرَّحْمَـانُ', meaning: 'The Most or Entirely Merciful'),
  AllahName(name: 'ٱلْرَّحِيْمُ', meaning: 'The Bestower of Mercy'),
  AllahName(name: 'ٱلْمَلِكُ', meaning: 'The King and Owner of Dominion'),
  AllahName(name: 'ٱلْقُدُّوسُ', meaning: 'The Absolutely Pure'),
  AllahName(name: 'ٱلْسَّلَامُ', meaning: 'The Perfection and Giver of Peace'),
  AllahName(
      name: 'ٱلْمُؤْمِنُ', meaning: 'The One Who gives Emaan and Security'),
  AllahName(
      name: 'ٱلْمُهَيْمِنُ',
      meaning: 'The Guardian, The Witness, The Overseer'),
  AllahName(name: 'ٱلْعَزِيزُ', meaning: 'The All Mighty'),
  AllahName(name: 'ٱلْجَبَّارُ', meaning: 'The Compeller, The Restorer'),
  AllahName(name: 'ٱلْمُتَكَبِّرُ', meaning: 'The Supreme, The Majestic'),
  AllahName(name: 'ٱلْخَالِقُ', meaning: 'The Creator, The Maker'),
  AllahName(name: 'ٱلْبَارِئُ', meaning: 'The Originator'),
  AllahName(name: 'ٱلْمُصَوِّرُ', meaning: 'The Fashioner'),
  AllahName(name: 'ٱلْغَفَّارُ', meaning: 'The All- and Oft-Forgiving'),
  AllahName(name: 'ٱلْقَهَّارُ', meaning: 'The Subduer, The Ever-Dominating'),
  AllahName(name: 'ٱلْوَهَّابُ', meaning: 'The Giver of Gifts'),
  AllahName(name: 'ٱلْرَّزَّاقُ', meaning: 'The Provider'),
  AllahName(name: 'ٱلْفَتَّاحُ', meaning: 'The Opener, The Judge'),
  AllahName(name: 'ٱلْعَلِيمُ', meaning: 'The All-Knowing, The Omniscient'),
  AllahName(name: 'ٱلْقَابِضُ', meaning: 'The Withholder'),
  AllahName(name: 'ٱلْبَاسِطُ', meaning: 'The Extender'),
  AllahName(name: 'ٱلْخَافِضُ', meaning: 'The Reducer, The Abaser'),
  AllahName(name: 'ٱلْرَّافِعُ', meaning: 'The Exalter, The Elevator'),
  AllahName(name: 'ٱلْمُعِزُّ', meaning: 'The Honourer, The Bestower'),
  AllahName(name: 'ٱلْمُذِلُّ', meaning: 'The Dishonourer, The Humiliator'),
  AllahName(name: 'ٱلْسَّمِيعُ', meaning: 'The All-Hearing'),
  AllahName(name: 'ٱلْبَصِيرُ', meaning: 'The All-Seeing'),
  AllahName(name: 'ٱلْحَكَمُ', meaning: 'The Judge, The Giver of Justice'),
  AllahName(name: 'ٱلْعَدْلُ', meaning: 'The Utterly Just'),
  AllahName(name: 'ٱلْلَّطِيفُ', meaning: 'The Subtle One, The Most Gentle'),
  AllahName(name: 'ٱلْخَبِيرُ', meaning: 'The Acquainted, The All-Aware'),
  AllahName(name: 'ٱلْحَلِيمُ', meaning: 'The Most Forbearing'),
  AllahName(name: 'ٱلْعَظِيمُ', meaning: 'The Magnificent, The Supreme'),
  AllahName(
      name: 'ٱلْغَفُورُ', meaning: 'The Forgiving, The Exceedingly Forgiving'),
  AllahName(name: 'ٱلْشَّكُورُ', meaning: 'The Most Appreciative'),
  AllahName(name: 'ٱلْعَلِيُّ', meaning: 'The Most High, The Exalted'),
  AllahName(name: 'ٱلْكَبِيرُ', meaning: 'The Greatest, The Most Grand'),
  AllahName(
      name: 'ٱلْحَفِيظُ',
      meaning: 'The Preserver, The All-Heedful and All-Protecting'),
  AllahName(name: 'ٱلْمُقِيتُ', meaning: 'The Sustainer'),
  AllahName(name: 'ٱلْحَسِيبُ', meaning: 'The Reckoner, The Sufficient'),
  AllahName(name: 'ٱلْجَلِيلُ', meaning: 'The Majestic'),
  AllahName(
      name: 'ٱلْكَرِيمُ', meaning: 'The Most Generous, The Most Esteemed'),
  AllahName(name: 'ٱلْرَّقِيبُ', meaning: 'The Watchful'),
  AllahName(name: 'ٱلْمُجِيبُ', meaning: 'The Responsive One'),
  AllahName(name: 'ٱلْوَاسِعُ', meaning: 'The All-Encompassing, The Boundless'),
  AllahName(name: 'ٱلْحَكِيمُ', meaning: 'The All-Wise'),
  AllahName(name: 'ٱلْوَدُودُ', meaning: 'The Most Loving'),
  AllahName(name: 'ٱلْمَجِيدُ', meaning: 'The Glorious, The Most Honorable'),
  AllahName(
      name: 'ٱلْبَاعِثُ', meaning: 'The Resurrector, The Raiser of the Dead'),
  AllahName(name: 'ٱلْشَّهِيدُ', meaning: 'The All- and Ever Witnessing'),
  AllahName(name: 'ٱلْحَقُّ', meaning: 'The Absolute Truth'),
  AllahName(
      name: 'ٱلْوَكِيلُ', meaning: 'The Trustee, The Disposer of Affairs'),
  AllahName(name: 'ٱلْقَوِيُّ', meaning: 'The All-Strong'),
  AllahName(name: 'ٱلْمَتِينُ', meaning: 'The Firm, The Steadfast'),
  AllahName(name: 'ٱلْوَلِيُّ', meaning: 'The Protecting Associate'),
  AllahName(name: 'ٱلْحَمِيدُ', meaning: 'The Praiseworthy'),
  AllahName(name: 'ٱلْمُحْصِيُ', meaning: 'The All-Enumerating, The Counter'),
  AllahName(name: 'ٱلْمُبْدِئُ', meaning: 'The Originator, The Initiator'),
  AllahName(name: 'ٱلْمُعِيدُ', meaning: 'The Restorer, The Reinstater'),
  AllahName(name: 'ٱلْمُحْيِى', meaning: 'The Giver of Life'),
  AllahName(name: 'ٱلْمُمِيتُ', meaning: 'The Bringer of Death, The Destroyer'),
  AllahName(name: 'ٱلْحَىُّ', meaning: 'The Ever-Living'),
  AllahName(name: 'ٱلْقَيُّومُ', meaning: 'The Sustainer, The Self-Subsisting'),
  AllahName(name: 'ٱلْوَاجِدُ', meaning: 'The Perceiver'),
  AllahName(name: 'ٱلْمَاجِدُ', meaning: 'The Illustrious, The Magnificent'),
  AllahName(name: 'ٱلْوَاحِدُ', meaning: 'The One'),
  AllahName(name: 'ٱلْأَحَد', meaning: 'The Unique, The Only One'),
  AllahName(name: 'ٱلْصَّمَدُ', meaning: 'The Eternal, Satisfier of Needs'),
  AllahName(name: 'ٱلْقَادِرُ', meaning: 'The Capable, The Powerful'),
  AllahName(name: 'ٱلْمُقْتَدِرُ', meaning: 'The Omnipotent'),
  AllahName(name: 'ٱلْمُقَدِّمُ', meaning: 'The Expediter, The Promoter'),
  AllahName(name: 'ٱلْمُؤَخِّرُ', meaning: 'The Delayer, The Retarder'),
  AllahName(name: 'ٱلأَوَّلُ', meaning: 'The First'),
  AllahName(name: 'ٱلْآخِرُ', meaning: 'The Last'),
  AllahName(name: 'ٱلْظَّاهِرُ', meaning: 'The Manifest'),
  AllahName(
      name: 'ٱلْبَاطِنُ', meaning: 'The Hidden One, Knower of the Hidden'),
  AllahName(name: 'ٱلْوَالِي', meaning: 'The Governor, The Patron'),
  AllahName(name: 'ٱلْمُتَعَالِي', meaning: 'The Self Exalted'),
  AllahName(
      name: 'ٱلْبَرُّ', meaning: 'The Source of Goodness, The Kind Benefactor'),
  AllahName(name: 'ٱلْتَّوَّابُ', meaning: 'The Ever-Pardoning, The Relenting'),
  AllahName(name: 'ٱلْمُنْتَقِمُ', meaning: 'The Avenger'),
  AllahName(name: 'ٱلْعَفُوُّ', meaning: 'The Pardoner'),
  AllahName(name: 'ٱلْرَّؤُفُ', meaning: 'The Most Kind'),
  AllahName(
      name: 'مَالِكُ ٱلْمُلْكُ',
      meaning: 'Master of the Kingdom, Owner of the Dominion'),
  AllahName(
      name: 'ذُو ٱلْجَلَالِ وَٱلْإِكْرَامُ',
      meaning: 'Possessor of Glory and Honour, Lord of Majesty and Generosity'),
  AllahName(name: 'ٱلْمُقْسِطُ', meaning: 'The Equitable, The Requiter'),
  AllahName(name: 'ٱلْجَامِعُ', meaning: 'The Gatherer, The Uniter'),
  AllahName(name: 'ٱلْغَنيُّ', meaning: 'The Self-Sufficient, The Wealthy'),
  AllahName(name: 'ٱلْمُغْنِيُّ', meaning: 'The Enricher'),
  AllahName(name: 'ٱلْمَانِعُ', meaning: 'The Withholder'),
  AllahName(name: 'ٱلْضَّارُ', meaning: 'The Distresser'),
  AllahName(name: 'ٱلْنَّافِعُ', meaning: 'The Propitious, The Benefactor'),
  AllahName(name: 'ٱلْنُّورُ', meaning: 'The Light, The Illuminator'),
  AllahName(name: 'ٱلْهَادِي', meaning: 'The Guide'),
  AllahName(name: 'ٱلْبَدِيعُ', meaning: 'The Incomparable Originator'),
  AllahName(name: 'ٱلْبَاقِي', meaning: 'The Ever-Surviving, The Everlasting'),
  AllahName(name: 'ٱلْوَارِثُ', meaning: 'The Inheritor, The Heir'),
  AllahName(name: 'ٱلْرَّشِيدُ', meaning: 'The Guide, Infallible Teacher'),
  AllahName(name: 'ٱلْصَّبُورُ', meaning: 'The Forbearing, The Patient')
];
